/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1_edd_plantasvrszombies;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollBar;

/**
 *
 * @author ROBIN
 */
public class Gui_Plantas extends javax.swing.JFrame {
    int y = 0;
    Lista_Plantas_Zombies listaPV = new Lista_Plantas_Zombies();
    /**
     * Creates new form Gui_Plantas
     */
    public Gui_Plantas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Btn_Agregar_Plantas = new javax.swing.JButton();
        Btn_Aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Imagen");

        jLabel2.setText("Nombre");

        jLabel3.setText("Cantidad Ataque");

        jLabel4.setText("Cantidad Defensa");

        jLabel5.setText("Tipo de Ataque");

        Btn_Agregar_Plantas.setText("Agregar");
        Btn_Agregar_Plantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Agregar_PlantasActionPerformed(evt);
            }
        });

        Btn_Aceptar.setText("Aceptar");
        Btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_Agregar_Plantas)
                .addGap(9, 9, 9)
                .addComponent(Btn_Aceptar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(94, 94, 94)
                .addComponent(jLabel2)
                .addGap(60, 60, 60)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(53, 53, 53)
                .addComponent(jLabel5)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 417, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Agregar_Plantas)
                    .addComponent(Btn_Aceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Agregar_PlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Agregar_PlantasActionPerformed
        // TODO add your handling code here:
        String path = "";
        JPanel p = new JPanel(); 
        p.setBounds(10, 50 + y, 670, 120);
        p.setBackground(Color.red); 
        JLabel foto = new JLabel();
        foto.setBounds(10, 10, 100, 100);
        JLabel nombre = new JLabel();
        nombre.setBounds(170, 40, 60, 15);
        JLabel CantAtaque = new JLabel();
        CantAtaque.setBounds(310, 40, 30, 15); 
        JLabel CantDef = new JLabel();
        CantDef.setBounds(440, 40, 30, 15);
        JLabel TipoAtaque = new JLabel();
        TipoAtaque.setBounds(570, 40, 60, 15);
        
        
        JFileChooser filechooser = new JFileChooser();
        filechooser.setDialogTitle("Abrir Archivo...");
        File file1 = new File("C:/Users/ROBIN/Google Drive/2015/1er Semestre/EDD/Laboratorio/Practica 1/Imagenes/Plantas");
        filechooser.setCurrentDirectory(file1); 
        int result = filechooser.showOpenDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            try {
                File file = filechooser.getSelectedFile();
                path = file.toString();
                ImageIcon icon = new ImageIcon(file.toString());
                Icon icono = new ImageIcon(icon.getImage().getScaledInstance(foto.getWidth(),foto.getHeight(),Image.SCALE_DEFAULT));
                foto.setIcon(icono);
                                
            } catch (Exception e) {
            }
        }
        
                foto.setVisible(true);
                p.add(foto); 
                p.setLayout(null); 
                this.add(p, BorderLayout.EAST);
                this.repaint();
                this.pack();
                
                nombre.setText(JOptionPane.showInputDialog(this,"Ingrese el nombre de la planta...").toString());
                p.add(nombre);
                this.repaint();
                
                CantAtaque.setText(JOptionPane.showInputDialog(this,"Ingrese la cantidad de ataque...").toString());
                p.add(CantAtaque);
                this.repaint();
                
                CantDef.setText(JOptionPane.showInputDialog(this, "Ingrese la Cantidad de Defensa..").toString());
                p.add(CantDef);
                this.repaint();
                
                TipoAtaque.setText(JOptionPane.showInputDialog(this, "Ingrese el tipo de ataque (Directo o Disparo)..")); 
                p.add(TipoAtaque);
                this.repaint();
                        
        listaPV.InsertAtBack(path, nombre.getText(), Integer.parseInt(CantAtaque.getText()),Integer.parseInt(CantDef.getText()),TipoAtaque.getText());
        
        y = y + 130;
    }//GEN-LAST:event_Btn_Agregar_PlantasActionPerformed

    private void Btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AceptarActionPerformed
        // TODO add your handling code here:
        Gui_Zombies z = new Gui_Zombies();
        z.setVisible(true);
        this.dispose();
        z.show();
    }//GEN-LAST:event_Btn_AceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_Plantas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Aceptar;
    private javax.swing.JButton Btn_Agregar_Plantas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
